# Generated by Django 4.2.5 on 2023-12-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_video_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
