# Generated by Django 4.2.5 on 2023-11-22 17:37

from django.db import migrations, models
import django.db.models.deletion
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_message_id_alter_relationship_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRelation',
            fields=[
                ('id', models.CharField(default=main.utils.get_random_id_message, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_msgr', to='main.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_msgr', to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('MSGRelation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.messagerelation')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_m', to='main.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_m', to='main.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
